ServerConfig:
  RunMode: info
  LogOut: stdout
TwitterConfig:
  OauthToken: ''
  OauthTokenSecret: ''
  ApiKey: ''
  ApiKeySecret: ''
  Bearer: ''
DiscordConfig:
  BotToken: ''
IpfsConfig:
  Api: ''
  HttpGateway: ''
