ServerConfig:
  RunMode: info
  LogOut: stdout
TwitterConfig:
  OauthToken: ''
  OauthTokenSecret: ''
  ApiKey: ''
  ApiKeySecret: ''
  Bearer: ''
DiscordConfig:
  BotToken: ''
IpfsConfig:
  Api: ''
  HttpGateway: ''
ChainConfig:
  Rpc: 'https://api.erbie.io/'
  NftAdminPriv: ''
  MaxMint: 10
GradioConfig:
  Url: ''
ComfyuiConfig:
  Host: 192.168.4.228
  Port: 3456